[modules]
autoload=yes

; Explicitly load ARI and AGI support
load => res_ari.so
load => res_ari_channels.so
load => res_ari_bridges.so
load => res_ari_recordings.so
load => res_ari_playbacks.so
load => res_agi.so
load => app_stasis.so
load => res_pjsip.so
load => res_pjsip_session.so
load => res_pjsip_sdp_rtp.so
load => res_pjsip_authenticator_digest.so
load => res_pjsip_endpoint_identifier_user.so
load => app_voicemail.so
load => app_dial.so
load => app_background.so
load => app_playback.so
load => app_waitexten.so
