[transport-udp-test]
type=transport
protocol=udp
bind=0.0.0.0:5061

[test1001]
type=endpoint
transport=transport-udp-test
context=from-ht812
disallow=all
allow=ulaw,alaw
aors=aor_test1001
direct_media=no

[aor_test1001]
type=aor
max_contacts=2
remove_existing=yes
