[general]
format=wav49|gsm|wav
serveremail=asterisk@pbx.local
attach=yes
skipms=3000
maxsilence=10
silencethreshold=128
maxlogins=3
emaildateformat=%A, %B %d, %Y at %r
pagerdateformat=%A, %B %d, %Y at %r
sendvoicemail=yes

[zonemessages]
eastern=America/New_York|'vm-received' Q 'digits/at' IMp
central=America/Chicago|'vm-received' Q 'digits/at' IMp
mountain=America/Denver|'vm-received' Q 'digits/at' IMp
pacific=America/Los_Angeles|'vm-received' Q 'digits/at' IMp

[default]
; Format: mailbox => password,Full Name,email@example.com,pager@example.com,options
1001 => 1234,Extension 1001,,
1002 => 1234,Extension 1002,,
